repos:
-   repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
    - id: black
      stages: [commit]
      entry: black --diff .

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      language_version: python3.11
      stages: [commit]