repos:
  - repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
    - id: flake8
      stages: [commit]

  - repo: https://github.com/ambv/black
    rev: master
    hooks:
    - id: black
      stages: [commit]
      args: ["--check", "--diff", "."]