version: '3'

services:
    talk_organizer:
        build: .
        image: talk_organizer_image
        container_name: talk_organizer_container
        command: uvicorn core.application:app --reload --host 0.0.0.0 --port 8000 --workers 8

        ports:
            - 8000:8000

        env_file:
            - .env

        volumes:
            - ./:/python_colombia/talk_organizer
